import "./globals.css";
import Providers from "./store/Provider";
// import { SessionProvider } from "next-auth/react";
// import { getSession } from "next-auth/react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const session = getSession();
  return (
    <html lang="en">
      <body>
          <Providers>{children}</Providers>
        {/* <SessionProvider session={session}>
        </SessionProvider> */}
      </body>
    </html>
  );
}
